/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  clientSdksSidebar: [
    { type: "doc", id: "index" },
    {
      type: "ref",
      id: "react/index",
      label: "React Library",
    },
    {
      type: "ref",
      id: "react-native/index",
      label: "React Native Library",
    },
    {
      type: "ref",
      id: "php/index",
      label: "PHP Library",
    },
  ],

  reactSidebar: [{ type: "autogenerated", dirName: "react" }],
  reactNativeSidebar: [{ type: "autogenerated", dirName: "react-native" }],
  phpSidebar: [{ type: "autogenerated", dirName: "php" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
